---
jenkins:
  groupname: "{{ override_jenkins_group | default('jenkins') }}"
  bind_addr: "{{ override_jenkins_bind_addr | default('localhost') }}"
  port: "{{ override_jenkins_port | default('8080') }}"
  username: "{{ override_jenkins_name | default('jenkins') }}"
  uid: "{{ override_jenkins_uid | default(1000)  }}"
  gid: "{{ override_jenkins_gid | default(1000)  }}"
  home: "{{ override_jenkins_home | default('/home/jenkins') }}"
  tools:
    home: "{{ override_jenkins_tools_home | default('/opt/tools') }}"
  executors:
    num: "{{ override_jenkins_num_executors | default(4) }}"
  default_jdk_home: '/opt/oracle/java'
  default_mvn_home: '/opt/apache/maven'
  default_mvn_settings: '/opt/tools/settings.xml'
  admin:
    id: 'admin'
    password: "{{ override_jenkins_password }}"
  ldap:
    search:
      group:
        base: "{{ override_ldap_group_search_base | default('') }}"
        filter: "{{ override_ldap_group_search_filter | default('') }}"
    inhibit_root_dn: false
    rootDn: "{{ override_ldap_root_dn | default('') }}"
    url: "{{ override_ldap_url | default('') }}"
  view:
    streams:
      - eap-7.1.x
      - eap-7.2.x
      - eap-7.3.x
      - wildfly
      - xp-2.0.x
    tabs:
      columns:
        - "status"
        - "weather"
        - "jobName"
        - "lastSuccess"
        - "lastFailure"
        - "lastDuration"
        - "buildButton"
  service:
    - name: hephaestus
      ip: "{{ known_hosts.jenkins.ip | default('10.88.0.3') }}"
      readwrite_volumes:
        - { src: '/home/jenkins', dest: '/var/jenkins_home' }
      add_hosts:
        - { src: "{{ known_hosts.podman.name }}", ip: "{{ known_hosts.podman.ip }}" }
        - { src: "{{ known_hosts.server.name }}", ip: "{{ known_hosts.server.ip }}" }
      ports_mapping:
       - { src: "{{ override_jenkins_port | default('8080') }}", dest: "{{ override_jenkins_port | default('8080') }}" }
