---
- assert:
    that:
      - nginx_config_dir is defined
      - nginx_config_dir != ""
    quiet: true

- name: "Ensure HTTP cache common config is created"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ nginx.username }}" 
    group: "{{ nginx.groupname }}"
    mode: 0644
  loop:
    - { src: templates/commons.d/maven.cache.conf.j2, dest: "{{ nginx_config_dir }}/commons.d/maven.cache.conf" }
    - { src: templates/commons.d/caches.conf.j2, dest: "{{ nginx_config_dir }}/commons.d/caches.conf" }

- name: "Ensure Maven Central cache directory is created"
  file:
    path: "{{ item.directory }}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0775
  loop: "{{ nginx.caches.directories }}"

- name: "Deploy settings.xml to use the caches"
  template:
    src: templates/settings.xml.j2
    dest: /opt/tools/settings.xml
    owner: jenkins
    group: jenkins
    mode: 0644

