---
- assert: 
    that:
      - item is defined
      - component_alignment is defined
      - component_alignment.config is defined
      - component_alignment.config.dir is defined   
      - component_alignment.config.baseurl is defined
    quiet: true

- set_fact:
   config_file_url: "{{ component_alignment.config.baseurl }}/{{ item }}"
   config_file_path: "{{ component_alignment.config.dir }}/{{ item }}"

- debug:
    msg: "{{ config_file_url }}"

- name: "Ensure component_alignment config file for {{ item }} is deployed as {{ config_file_path }}"
  get_url:
    url: "{{ config_file_url }}"
    dest: "{{ config_file_path }}"
    validate_certs: no
  register: res
  changed_when:
    - res.checksum_dest != res.checksum_src
    - not ansible_check_mode
 
- name: "Ensure config file {{ config_file_path }} has appropriate owner, group and mode."
  file:
    path: "{{ config_file_path }}"
    owner: jenkins
    group: jenkins
    mode: 0644
