---
- assert:
    that:
      - monit is defined
      - monit.alerts is defined
      - monit.alerts.disk_usage is defined
      - (monit.alerts.disk_usage | length ) > 0
    quiet: true

- name: "Set up Monit alert on disk usage"
  template:
    src: templates/monit.disk.j2
    dest: "/etc/monit.d/{{ item.name }}"
  with_items: "{{ monit.alerts.disk_usage }}"
