- set_fact: package_name=docker
- name: Ensure Docker is installed
  import_tasks: tasks/rpminfo.yml

- name: Adding user {{ user.name }} to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
  loop: "{{ docker_users_list }}"
  loop_control:
    loop_var: user

- name: Set up service configuration
  copy:
    src: files/docker.conf
    dest: /etc/sysconfig/docker
    owner: root
    group: root

- name: "Run Docker Daemon"
  service:
    name: docker
    state: started
    enabled: yes
