- set_fact: package_name=docker
- name: Ensure Docker is installed
  import_tasks: tasks/rpminfo.yml

- name: Adding user {{ user.name }} to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
  loop: "{{ docker_users_list }}"
  loop_control:
    loop_var: user

- name: Set up service configuration
  copy:
    src: files/docker.conf
    dest: /etc/sysconfig/docker
    owner: root
    group: root

- name: "Run Docker Daemon"
  service:
    name: docker
    state: started
    enabled: yes

- name: "Install python docker packages"
  pip:
    name: docker

- name: "Create postgresql volume"
  docker_volume:
    volume_name: pgdata

- name: "Create and start postgreql"
  docker_container:
    name: "{{ postgres_db.name }}"
    image: postgres
    ports:
      - "{{ postgres_db.port }}:5432"
    state: started
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    env:
      POSTGRES_PASSWORD: "{{ postgres_db.password }}"