- set_fact: package_name={{ jboss.package_name }}
- name: "Ensures jboss-eap7 RPM package is installed"
  import_tasks: tasks/rpminfo.yml

- set_fact: package_name={{ jboss.saml_adapter_package_name }}
- name: "Ensures Keycloak SAML adapter RPM package is installed"
  import_tasks: tasks/rpminfo.yml

#- name: "Install Keycloak SAML adapter into EAP"
#  command: "{{ jboss.home }}/bin/jboss-cli.sh --file=files/adapter-install-saml-offline.cli -Dserver.config={{ jboss.config }}"

- name: "Created config directory for jboss-eap7"
  file:
    path: /etc/jboss-eap7/
    state: directory
    group: jboss
    owner: jboss

- name: "Deploy configuration for jboss-eap7"
  template:
    src: templates/eap7-standalone.service.j2
    dest: /usr/lib/systemd/system/eap7-standalone.service
    group: jboss
    owner: jboss

- name: "Set up module dir for Postgres JDBC Driver"
  file:
    path: "{{ jboss.home }}/modules/org/postgresql/main/"
    state: directory
    group: jboss
    owner: jboss

- name: "Deploy JDBC driver for PQSL"
  copy:
    src: files/postgresql-8.4-703.jdbc4.jar
    dest: "{{ jboss.home }}/modules/org/postgresql/main/"
    group: jboss
    owner: jboss

- name: "Deploy module.xml"
  copy:
    src: files/module.xml
    dest: "{{ jboss.home }}/modules/org/postgresql/main/module.xml"
    group: jboss
    owner: jboss

- name: "Ensure JBoss EAP 7 is running"
  service:
    name: 'eap7-standalone'
    state: started
    enabled: yes

- name: "Tuning Wildfly using JCliff (CLI running on port {{ 9990 + jboss.port_shift|int }})"
  jcliff:
    wfly_home: /opt/rh/eap7/root/usr/share/wildfly/
    management_port: "{{ jboss.port_shift|int + 9990 }}"
    subsystems:
      - system_props:
        - name: jcliff.enabled
          value: true
        - name: aphrodite.config
          value: /home/jboss/prbz-overview/aphrodite.properties.json
        - name: payload.properties
          value: /home/jboss/prbz-overview/payload.properties
        - name: cacheDir
          value: /home/jboss/cache
        - name: cacheName
          value: github-cache
        - name: cacheSize
          value: 20
        - name: java.util.logging.manager
          value: org.jboss.logmanager.LogManager
      - drivers:
        - driver_name: postgresql
          driver_module_name: org.postgresql
          driver_xa_datasource_class_name: org.postgresql.xa.PGXADataSourcer
      - datasources:
        - name: "{{ mjolnir_ds.name }}"
          pool_name: "{{ mjolnir_ds.pool_name }}"
          enabled: true
          use_java_context: "{{ mjolnir_ds.use_java_context }}"
          jndi_name: "{{ mjolnir_ds.jndi_name }}"
          connection_url: "{{ mjolnir_ds.connection_url }}"
          driver_name: "{{ mjolnir_ds.driver_name }}"
          user_name: "{{ mjolnir_ds.user_name }}"
          password: "{{ mjolnir_ds.password }}"
        - name: "{{ mjolnir_dev_ds.name }}"
          pool_name: "{{ mjolnir_dev_ds.pool_name }}"
          enabled: true
          use_java_context: "{{ mjolnir_dev_ds.use_java_context }}"
          jndi_name: "{{ mjolnir_dev_ds.jndi_name }}"
          connection_url: "{{ mjolnir_dev_ds.connection_url }}"
          driver_name: "{{ mjolnir_dev_ds.driver_name }}"
          user_name: "{{ mjolnir_dev_ds.user_name }}"
          password: "{{ mjolnir_dev_ds.password }}"
