- set_fact:
    package_name: "{{ jboss.package_name }}"

- name: "Ensures jboss-eap7 RPM package is installed"
  import_tasks: tasks/rpminfo.yml

- name: "Deploy SystemD configuratuon for jboss-eap7"
  template:
    src: templates/eap7-standalone.service.j2
    dest: /usr/lib/systemd/system/eap7-standalone.service
    group: root
    owner: root

- name: "Deploy configuration for jboss-eap7"
  template:
    src: templates/eap7-standalone.conf.j2
    dest: /etc/opt/rh/eap7/wildfly/eap7-standalone.conf
    group: jboss
    owner: jboss

- name: "Set up module dir for Postgres JDBC Driver"
  file:
    path: "{{ jboss.home }}/modules/org/postgresql/main/"
    state: directory
    group: jboss
    owner: jboss

- name: "Deploy JDBC driver for PQSL"
  copy:
    src: files/postgresql-8.4-703.jdbc4.jar
    dest: "{{ jboss.home }}/modules/org/postgresql/main/"
    group: jboss
    owner: jboss

- name: "Deploy module.xml"
  copy:
    src: files/module.xml
    dest: "{{ jboss.home }}/modules/org/postgresql/main/module.xml"
    group: jboss
    owner: jboss

- name: "Ensure JBoss EAP 7 is running"
  service:
    name: 'eap7-standalone'
    state: started
    enabled: yes

- name: "Wait for EAP7 to start"
  wait_for:
    timeout: 5
  delegate_to: localhost

- name: "Tuning Wildfly using JCliff (CLI running on port {{ 9990 + jboss.port_shift|int }})"
  jcliff:
    wfly_home: /opt/rh/eap7/root/usr/share/wildfly/
    management_port: "{{ jboss.port_shift|int + 9990 }}"
    subsystems:
      - system_props:
        - name: jcliff.enabled
          value: true
        - name: aphrodite.config
          value: /home/jboss/prbz-overview/aphrodite.properties.json
        - name: payload.properties
          value: /home/jboss/prbz-overview/payload.properties
        - name: cacheDir
          value: /home/jboss/cache
        - name: cacheName
          value: github-cache
        - name: cacheSize
          value: 20
        - name: java.util.logging.manager
          value: org.jboss.logmanager.LogManager
