- name: Check files attributes and ownership on /usr/share
  file: state=directory owner=root group=root mode=0755 dest=/usr/share

- name: Check /etc/security/limits.conf is correct
  copy: src=limits.conf dest=/etc/security/limits.conf owner=root group=root mode=0644

- name: Check if group docker exists
  group: name=docker state=present

- name: Check that docker user are in group
  user: name={{ item }} groups=docker append=yes
  with_items:
  - belaran

- name: Add a specific motd
  copy: src=files/motd dest=/etc/motd owner=root group=root mode=0644
