---
podman_services: []
ares:
  home: "{{ podman_images_home_override | default('/home/jenkins/ares.git') }}"
  owner: "{{ podman_images_user_ovveride | default('jenkins') }}"
  group: "{{ podman_images_user_ovveride | default('jenkins') }}"
  git:
    repo: "{{ podman_images_git_repo_override | default('git@github.com:jboss-set/ares.git') }}"
    branch: "{{ podman_images_git_branch_override | default('olympus') }}"
    keyfile: '/home/jenkins/.ssh/jboss_set_github_rsa'
  folder_name: "{{ podman_images_git_folder_name_override | default('ares.git') }}"
