---
- assert:
    that:
      - podman is defined
      - podman.home is defined
      - podman_services is defined
      - podman_services | length > 0
    quiet: yes

- name: "Ensure podman home is created: {{ podman.home }}"
  file:
    path: "{{ podman.home }}"
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: "Deploy script to start/stop podman based services"
  template:
    src: templates/podman-service.sh.j2
    dest: "{{ podman.home }}/podman-service.sh"
    owner: root
    group: root
    mode: 0755

- name: "Add podman based services to systemd"
  include_role:
    name: systemd
    tasks_from: podman.yml
  loop: "{{ podman_services }}"
