---
- set_fact:
    yum_module_name: container-tools

- name: "Check if {{ yum_module_name }}"
  command: >
    yum module list --installed  {{ yum_module_name }}
  register: is_yum_module_installed
  changed_when: false

- name: "Install yum module for Podman"
  command: >
    yum module install -y container-tools
  when:
    - is_yum_module_installed.rc

- include_role:
    name: fast_yum_install
  vars:
    package_name: "{{ item }}"
  loop: "{{ podman.packages }}"

- name: "Ensure user namespaces has been increased"
  template:
    src: templates/userns.conf.j2
    dest: "{{ podman.kernel.user_namespaces_config_file }}"
  notify:
    - sysctl-userns

- name: "Ensure podman service is running"
  service:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
  loop:
    - { name: podman.socket, enabled: yes, state: started }
    - { name: podman, enabled: yes, state: stopped }
      #    - { name: podman.slice, enabled: yes, state: stopped }

- name: "Ensures jenkins can use podman"
  command: loginctl enable-linger jenkins
  changed_when: false

- name: "Ensures any user can access podman keys (podman pull)"
  file:
    dest: /etc/docker/certs.d/
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    recurse: yes
