---
- assert:
    that:
      - kdump is defined
      - kdump.level is defined
      - kdump.level != ""

- name: Check kdump configuration
  template:
    src: templates/kdump.j2
    dest: /etc/kdump.conf
    mode: 644
    owner: root
    group: root
