---
- assert:
    that:
      - item is defined
      - item.image_name is defined
      - item.script is defined
      - item.volume is defined
      - item.volume.src is defined
      - item.volume.dest is defined
      - item.owner is defined
    quiet: true

- set_fact:
    volume: "{{ item.volume.src }}:{{ item.volume.dest }}:rw"

- name: "Retrieve image id for tag {{ item.tag }} if exists."
  command: "runuser -l {{ item.owner }} -c 'podman run -v {{ volume }} -ti {{ item.image_name }} {{ item.script }}'"
  register: run_results 
  changed_when: false

- debug:
    msg: "{{ run_results }}"

