---
- assert:
    that: 
      - old_releases.dir is defined
      - old_releases.dir != ""
      - old_releases.url is defined
      - old_releases.url != ""
    quiet: true

- stat:
    path: "{{ old_releases.dir }}"
  register: old_releases_dir_path

- block:
  - name: "Create old releases folder for test jobs"
    file:
      path: "{{ old_releases.dir }}"
      state: directory
      group: root
      owner: root
    when: not old_releases_dir_path.stat.exists
  
  # providing a file name for dest means those will only be downloaded if not present to start with
  - name: "Download old EAP7 releases"
    get_url:
      url: "{{ old_releases.url }}/eap7/{{ item }}/jboss-eap-{{ item }}.zip"
      dest: "{{ old_releases.dir }}/jboss-eap-{{ item }}.zip"
    retries: 3
    delay: 5
    with_items:
      - 7.0.0
      - 7.1.0
      - 7.2.0
      - 7.3.0

  - name: "Download old EAP6 releases"
    get_url:
      url: "{{ old_releases.url }}/eap6/{{ item }}/jboss-eap-{{ item }}.zip"
      dest: "{{ old_releases.dir }}/jboss-eap-{{ item }}.zip"
    retries: 3
    delay: 5
    with_items:
      - 6.1.0
      - 6.1.1
      - 6.2.0
      - 6.3.0
      - 6.4.0
  
  # URL pattern for 6.0.0 and 6.0.1 is different
  - name: "Download 6.0.x EAP6 releases"
    get_url:
      url: "{{ old_releases.url }}/eap6/{{ item }}/zip/jboss-eap-{{ item }}.zip"
      dest: "{{ old_releases.dir }}/jboss-eap-{{ item }}.zip"
    retries: 3
    delay: 5
    with_items:
      - 6.0.0
      - 6.0.1
  when: old_releases_dir_path is defined
