---
pr_processor_version: "{{ override_pr_processor_version | default('0.8.8.Final') }}"
pr_processor:
  home: "{{ override_pr_processor_home | default('/opt/tools/pr-processor/') }}"
  url: "https://repository.jboss.org/org/jboss/set/pull-processor/{{ pr_processor_version }}/pull-processor-{{ pr_processor_version }}.jar"
  owner: "{{ override_pr_processor_owner | default('jenkins') }}"
  group: "{{ override_pr_processor_group | default('jenkins') }}"
  version: "{{ pr_processor_version }}"
