---
podman:
  home: /opt/podman
  packages:
    - slirp4netns
    - podman
    - podman-docker
  kernel:
    max_user_namespaces: 28633
    user_namespaces_config_file: /etc/sysctl.d/userns.conf
  images:
    remotes:
      - { name: 'docker.io/library/nginx' }
    locals:
      - { name: 'automatons', owner: 'jenkins', tag: 'automatons' }
      - { name: 'bashomatons', owner: 'jenkins', tag: 'bashomatons' }
      - { name: 'hephaestus', owner: 'root', tag: 'hephaestus' }
      - { name: 'jenkins-job-builder', owner: 'jenkins', tag: 'jbb' }
