---
- include_role:
    name: fast_yum_install
  vars:
    package_name: openssh-server

- name: "Checks SSHd configuration"
  template: 
    src: templates/sshd_config.j2 
    dest: /etc/ssh/sshd_config 
    group: root 
    owner: root
  notify:
    - restart sshd

- name: "Ensure SSH traffic is allowed"
  firewalld:
    service: ssh
    permanent: yes
    state: enabled

- name: "Ensure SSHd is running"
  service:
    name: sshd
    state: started
    enabled: yes
